### ISSUE TITLE
Dimensions seems to be wrong

### ISSUE THREAD

**Issue by xobtoor** [olkb/olkb_parts#2]
Something with the dimensions seems wrong or i'm making some mistakes.

This is visible in multiple Programms like Fusion360, slic3r, inkscape, and cura

Examples:
![planck_dimenseions](https://cloud.githubusercontent.com/assets/313188/20640679/296f0cb6-b3e5-11e6-9443-4d0e490a2d71.JPG)

![planck_dimensions2](https://cloud.githubusercontent.com/assets/313188/20640699/a47b26a6-b3e5-11e6-8adc-c6c7456b5bec.JPG)

Only the bottom part seems right.
![planck_dimensions3](https://cloud.githubusercontent.com/assets/313188/20640742/63e9fbb0-b3e7-11e6-9829-8d39018fb377.JPG)

**Comment by jackhumbert** [comment]
Thanks, yeah - I broke the cardinal rule and scaled the drawing :/ Planck tops plates should be scaled to 233mm on their largest dimension. I'll get them fixed here later today.

**Comment by jpotier** [comment]
Hey, atomic dxf's seem to display the same problem. I have a spare top plate and would like to have the other parts printed, but the dimensions are wrong. Could you give it a quick update too?
