### ISSUE TITLE
lo-pro mx plate

### ISSUE THREAD

**Issue by anthonyrichir** [olkb/olkb_parts#4]
Hi,

I don't see the stl for the lo-pro plate for MX switches, is it available ?
I just ordered a Planck via Massdrop but didn't received the plate and I'm not getting answer from the support, I thought I could build one myself if I find someone to produce it from the stl.

Thanks in advance

**Comment by KTSCode** [comment]
I would also like an stl for the lo-pro plate for MX switches

**Comment by anthonyrichir** [comment]
Any chance to get an answer @jackhumbert ?

**Comment by ChasingAir** [comment]
I would also really like this!

**Comment by jackhumbert** [comment]
[Just uploaded this!](https://github.com/olkb/olkb_parts/blob/master/planck/lo-pro-plate-mx-2x2u.stl) :)

**Comment by anthonyrichir** [comment]
Nice ! Thank you very much !
