### ISSUE TITLE
Preonic Rev3 Hi-Pro Mod Case Bottom STL

### ISSUE THREAD

**Issue by equalunique** [olkb/olkb_parts#7]
Hi,

I noticed that while the other case files are found in olkb_parts/preonic, the file for the mod case is missing. Can this please be added?

Thanks!

**Comment by equalunique** [comment]
Would really appreciate it this could be added since I have some other 3D printed parts and would *love* a Preonic case in matching filament.

**Comment by boboysdadda** [comment]
I'd like to 2nd this. Saw the run for the mod kit on Massdrop and it looks like it only ran that 1 time. 
https://drop.com/buy/massdrop-x-olkb-preonic-utility-kit 

Anyone else who would like to do it will likely have to source the parts on their own. The case being the hardest part. Please make this available to us if possible.

Thanks again for such and awesome keeb

**Comment by jackhumbert** [comment]
Uploaded :) https://github.com/olkb/olkb_parts/blob/master/preonic/preonic-rev3-hipro-mod.stl
